// big-num: replacement for crypto/fipsmodule/bcm.cc.
//
// bcm.cc is BoringSSL's unity TU for the entire FIPS module — it #includes
// every algorithm (AES, EC, RSA, ML-DSA, …) so the static integrity check can
// hash one contiguous .text section. big-num only needs BIGNUM, and the only
// transitive deps are what BN_rand / BN_generate_prime_ex pull in (the
// CTR-DRBG, which needs AES + a SHA for entropy whitening). Everything else
// from the FIPS module is omitted.
//
// We never define BORINGSSL_FIPS in this build, so the integrity check and
// power-on-self-test machinery are #ifdef-ed out and don't link in.
//
// This file is generated by scripts/vendor-boringssl-2.sh — do not edit by
// hand; edit the heredoc in the script and re-vendor instead.

#if !defined(_GNU_SOURCE)
#define _GNU_SOURCE
#endif

#include <CBigNumBoringSSL_crypto.h>
#include "../bcm_support.h"
#include "../internal.h"
#include "bcm_interface.h"

OPENSSL_CLANG_PRAGMA("clang diagnostic push")
OPENSSL_CLANG_PRAGMA("clang diagnostic ignored \"-Wheader-hygiene\"")

// AES — needed by the CTR-DRBG (ECB only). The CBC / CFB / OFB / CTR public
// wrappers in aes/mode_wrappers.cc.inc are not built; they pull in cipher/.
#include "aes/aes.cc.inc"
#include "aes/aes_nohw.cc.inc"

// BIGNUM.
#include "bn/add.cc.inc"
#include "bn/asm/x86_64-gcc.cc.inc"
#include "bn/bn.cc.inc"
#include "bn/bytes.cc.inc"
#include "bn/cmp.cc.inc"
#include "bn/ctx.cc.inc"
#include "bn/div.cc.inc"
#include "bn/div_extra.cc.inc"
#include "bn/exponentiation.cc.inc"
#include "bn/gcd.cc.inc"
#include "bn/gcd_extra.cc.inc"
#include "bn/generic.cc.inc"
#include "bn/jacobi.cc.inc"
#include "bn/montgomery.cc.inc"
#include "bn/montgomery_inv.cc.inc"
#include "bn/mul.cc.inc"
#include "bn/prime.cc.inc"
#include "bn/random.cc.inc"
#include "bn/rsaz_exp.cc.inc"
#include "bn/shift.cc.inc"
#include "bn/sqrt.cc.inc"

// CTR-DRBG + the rand glue BN_rand calls into.
#include "rand/ctrdrbg.cc.inc"
#include "rand/rand.cc.inc"

// Entropy whitening for the DRBG seed. jitter.cc.inc transitively includes
// entropy/sha512.cc.inc; do not include the latter directly.
#include "entropy/jitter.cc.inc"

// SHA-256 / SHA-512 — used by the entropy path.
#include "sha/sha256.cc.inc"
#include "sha/sha512.cc.inc"

OPENSSL_CLANG_PRAGMA("clang diagnostic pop")

using namespace bssl;

// service_indicator/service_indicator.cc.inc unconditionally #includes
// evp/internal.h, ec.h, etc., which we no longer ship. In non-FIPS builds it
// only defines two trivial stubs, inlined here.
namespace bssl {
uint64_t FIPS_service_indicator_before_call() { return 0; }
uint64_t FIPS_service_indicator_after_call() { return 1; }
}  // namespace bssl
